### ISSUE TITLE
Chapter 5 page 118 specify the database initialization scripts

### ISSUE THREAD

**Issue by quaeast** [habuma/spring-in-action-5-samples#64]
It should add `classpath:` before each script

```yml
spring:
  datasource:
    schema:
      - classpath:schema.sql
```
